//
//  UIColor+AppPalette.h
//
//  This source file is autogenerated.
//  Don't change this file manually.
//

import UIKit

extension UIColor {

    class func primaryColor() -> UIColor {
        return UIColor(red: 0.1294117718935013,
            green:0.8078431487083435,
            blue:0.6000000238418579,
            alpha:1)
    }

    class func transparentPrimaryColor() -> UIColor {
        return UIColor(red: 0.1294117718935013,
            green:0.8078431487083435,
            blue:0.6000000238418579,
            alpha:0.09803921729326248)
    }

    class func lightPrimaryColor() -> UIColor {
        return UIColor(red: 0.8274509906768799,
            green:0.9607843160629272,
            blue:0.9215686321258545,
            alpha:1)
    }

    class func secondaryColor() -> UIColor {
        return UIColor(red: 0.95686274766922,
            green:0.1529411822557449,
            blue:0.3254902064800262,
            alpha:1)
    }

    class func lightSecondaryColor() -> UIColor {
        return UIColor(red: 0.9921568632125854,
            green:0.8313725590705872,
            blue:0.8666666746139526,
            alpha:1)
    }

    class func primaryTextColor() -> UIColor {
        return UIColor(red: 0.105882354080677,
            green:0.2156862765550613,
            blue:0.2705882489681244,
            alpha:1)
    }

    class func secondaryTextColor() -> UIColor {
        return UIColor(red: 0.6941176652908325,
            green:0.7490196228027344,
            blue:0.7686274647712708,
            alpha:1)
    }

    class func invalidStateColor() -> UIColor {
        return UIColor(red: 0.9333333373069763,
            green:0.239215686917305,
            blue:0.1490196138620377,
            alpha:1)
    }

    class func borderColor() -> UIColor {
        return UIColor(red: 0.6941176652908325,
            green:0.7490196228027344,
            blue:0.7686274647712708,
            alpha:1)
    }

}
